using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using KeePassLib;
using KeePassLib.Keys;

namespace WinUp {
    internal static class AdvancedWorkflowProbe {
        [System.Runtime.InteropServices.DllImport("user32.dll")]static extern IntPtr GetThreadDesktop(uint id);
        [System.Runtime.InteropServices.DllImport("kernel32.dll")]static extern uint GetCurrentThreadId();
        [System.Runtime.InteropServices.DllImport("user32.dll",SetLastError=true)]static extern IntPtr OpenInputDesktop(uint flags,bool inherit,uint access);
        [System.Runtime.InteropServices.DllImport("user32.dll")]static extern bool CloseDesktop(IntPtr h);
        [System.Runtime.InteropServices.DllImport("user32.dll",CharSet=System.Runtime.InteropServices.CharSet.Unicode)]static extern bool GetUserObjectInformation(IntPtr h,int index,StringBuilder name,int size,out int needed);
        static string DesktopName(IntPtr h){int needed;var text=new StringBuilder(256);return h==IntPtr.Zero?"none":GetUserObjectInformation(h,2,text,512,out needed)?text.ToString():"unavailable";}
        const string Password="Synthetic-Advanced-2026!";static int passed,failed;
        static void Check(string name,bool ok){Console.WriteLine((ok?"PASS ":"FAIL ")+name);if(ok)passed++;else failed++;}
        static bool Fails(Action action){try{action();return false;}catch(IOException){return true;}catch(InvalidDataException){return true;}}
        [STAThread]static int Main(string[] args){Console.SetOut(new StreamWriter(Console.OpenStandardOutput(),new UTF8Encoding(false)){AutoFlush=true});
            if(Environment.UserName!="WDAGUtilityAccount"&&!(args.Contains("--ci")&&Environment.GetEnvironmentVariable("GITHUB_ACTIONS")=="true"&&Paths.Root.StartsWith(@"C:\WinUpAudit\",StringComparison.OrdinalIgnoreCase)))throw new Exception("Synthetic sandbox only");
            AppDomain.CurrentDomain.AssemblyResolve+=(s,e)=>new AssemblyName(e.Name).Name=="KeePassLib"?CoreLoader.Resolve():EmbeddedModules.Resolve(e.Name);
            try{if(args.Contains("--file-only")){string root=Path.Combine(Paths.Root,"repair-"+Guid.NewGuid().ToString("N").Substring(0,8));Directory.CreateDirectory(root);FileRepair(root);}else Run();}catch(Exception ex){Console.WriteLine("FAIL exception "+ex);failed++;}Console.WriteLine("RESULT passed="+passed+" failed="+failed);return failed==0?0:1;
        }
        static void Run(){string root=Path.Combine(Paths.Root,"advanced-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
            var store=KdbxStore.Create(Password,null);try{
                string top=store.CreateAccountGroup(null,"Работа"),child=store.CreateAccountGroup(top,"Проект");
                var main=new LoginEntry{Name="Main",Login="synthetic@example.com",Password="Synthetic-main!",GroupId=child,Tags=KdbxStore.ParseTags("Проект; Работа; проект"),AutoTypeSequence="{USERNAME}{TAB}{PASSWORD}{ENTER}"};main.AutoTypeRules.Add(new AppWindowRule{Window="*Login*",Sequence="{PASSWORD}"});store.Entries.Add(main);store.Save();string id=main.Id;
                Check("nested-groups-tags-native-roundtrip",main.Tags.Count==2&&store.AccountGroups().Single(g=>g.Id==child).Path=="Работа / Проект"&&store.InAccountGroup(main,top));
                Check("group-cycle-and-nonempty-delete-refused",Fails(()=>store.ChangeAccountGroup(top,child,"Работа"))&&Fails(()=>store.DeleteAccountGroup(child)));
                store.ChangeAccountGroup(child,null,"Перенесённый проект");store.Save();Check("group-move-keeps-account",store.Entries.Single().Id==id&&store.Entries.Single().GroupId==child);
                string attachment=Path.Combine(root,"license.txt");File.WriteAllText(attachment,"Synthetic license",Encoding.UTF8);store.AddAttachment(id,attachment);store.Save();string exported=Path.Combine(root,"export.txt");store.ExportAttachment(id,"license.txt",exported);Check("attachment-encrypted-record-export-exact",File.ReadAllBytes(attachment).SequenceEqual(File.ReadAllBytes(exported))&&store.Attachments(id).Single().Name=="license.txt");
                Check("attachment-duplicate-refused",Fails(()=>store.AddAttachment(id,attachment)));string huge=Path.Combine(root,"too-big.dat");using(var f=File.Create(huge))f.SetLength(2*1024*1024+1);Check("attachment-size-bound",Fails(()=>store.AddAttachment(id,huge)));
                store.RemoveAttachment(id,"license.txt");store.Save();int version=store.Versions(id,false).First(v=>v.Index>=0&&store.HistoryEntry(id,v.Index).Name=="Main").Index;store.RestoreHistory(id,version,false);store.Save();Check("attachment-history-restores-file",store.Attachments(id).Count==1);
                main=store.Entries.Single(e=>e.Id==id);var linked=new LoginEntry{Name="Linked",Login=KdbxStore.Reference(id,'U'),Password=KdbxStore.Reference(id,'P'),GroupId=top};store.Entries.Add(linked);store.Save();string linkedId=linked.Id;Check("references-use-secret-and-login-without-changing-raw",linked.UsePassword(p=>p=="Synthetic-main!")&&linked.ResolvedLogin=="synthetic@example.com"&&linked.Password.StartsWith("{REF:"));
                main.Password="Synthetic-new!";linked.Target="https://example.org/";store.Save();Check("shared-password-change-propagates",linked.UsePassword(p=>p=="Synthetic-new!"));
                ReferenceImportScenarios(store,id);
                string csv=Encoding.UTF8.GetString(Export.Csv(new System.Collections.Generic.List<LoginEntry>{linked},null));Check("portable-export-materializes-login-and-password-references",csv.Contains("synthetic@example.com")&&csv.Contains("Synthetic-new!")&&!csv.Contains("{REF:"));
                Check("root-group-filter-does-not-include-nested-groups",!store.InAccountGroup(main,store.AccountGroups().First(g=>g.ParentId==null).Id));
                store.Lock();int left;StoreResult status;store=KdbxStore.Open(Password,null,out left,out status);main=store.Entries.Single(e=>e.Id==id);linked=store.Entries.Single(e=>e.Id==linkedId);Check("nested-account-reference-rule-after-reopen",main.GroupId==child&&main.AutoTypeRules.Count==1&&main.AutoTypeSequence.Contains("PASSWORD")&&linked.UsePassword(p=>p=="Synthetic-new!"));
                Check("references-do-not-mutate-source-login",linked.ResolvedLogin==main.Login&&main.Login=="synthetic@example.com");
                main.Password=KdbxStore.Reference(linkedId,'P');store.Save();Check("reference-cycle-refused",Fails(()=>linked.UsePassword(p=>p.Length)));main.Password="Synthetic-new!";store.Save();store.Entries.Remove(main);store.Save();main.ClearSecrets();Check("reference-missing-target-refused",Fails(()=>linked.UsePassword(p=>p.Length)));store.RestoreDeleted(id);store.Save();main=store.Entries.Single(e=>e.Id==id);linked=store.Entries.Single(e=>e.Id==linkedId);Check("trash-restores-original-group-and-references",main.GroupId==child&&linked.UsePassword(p=>p=="Synthetic-new!"));
                string otherPath=Path.Combine(root,"other.kdbx");store.SaveBeforeMerge(otherPath);var other=new PwDatabase();try{var composite=new CompositeKey();composite.AddUserKey(new KcpPassword(Password));KdbxSafety.OpenDatabase(other,otherPath,composite,null);var entry=other.RootGroup.FindEntry(new PwUuid(KeePassLib.Utility.MemUtil.HexStringToByteArray(id)),true);entry.CreateBackup(other);entry.Strings.Set("Password",new KeePassLib.Security.ProtectedString(true,"Synthetic-remote!"));entry.LastModificationTime=DateTime.UtcNow.AddMinutes(1);other.Save(null);}finally{other.Close();}
                using(var preview=store.PreviewMerge(otherPath,Password,null)){Check("merge-preview-conflict-no-changes",preview.SameDatabase&&preview.Conflicts.Count==1&&main.UsePassword(p=>p=="Synthetic-new!"));preview.Conflicts[0].Choice="Эта база";store.ApplyMerge(preview);store.Save();}
                main=store.Entries.Single(e=>e.Id==id);linked=store.Entries.Single(e=>e.Id==linkedId);Check("merge-local-choice-history-attachments-groups",main.UsePassword(p=>p=="Synthetic-new!")&&store.Attachments(id).Count==1&&main.GroupId==child&&store.Versions(id,false).Count>0);
                using(var preview=store.PreviewMerge(otherPath,Password,null)){preview.Conflicts[0].Choice="Вторая копия";store.ApplyMerge(preview);store.Save();}Check("merge-remote-choice-updates-linked-secret",store.Entries.Single(e=>e.Id==linkedId).UsePassword(p=>p=="Synthetic-remote!"));
                using(var preview=store.PreviewMerge(otherPath,Password,null)){store.Entries.Single(e=>e.Id==id).Notes="Changed after preview";store.Save();Check("merge-stale-preview-refused",Fails(()=>store.ApplyMerge(preview)));}
                MergeLocationsAndDeletions(store,root,id,child);
                Check("autotype-supported-parser",ApplicationAutoType.Parse("{CLEARFIELD}{USERNAME}{TAB 2}{DELAY 100}{S:Token}{SHIFT+TAB}{PASSWORD}{ENTER}").Count==9);
                Check("autotype-invalid-sequence-refused",Fails(()=>ApplicationAutoType.Parse("{UNKNOWN}"))&&Fails(()=>ApplicationAutoType.Parse("{DELAY 999999}"))&&Fails(()=>ApplicationAutoType.Parse("{PASSWORD")));
                Check("autotype-windows-wildcard-and-per-window-sequence",ApplicationAutoType.WindowMatches("*Login?","Synthetic Login1")&&ApplicationAutoType.SequenceFor(main,"Synthetic Login1")=="{PASSWORD}");
            }finally{store.Lock();}
            if(Environment.GetEnvironmentVariable("GITHUB_ACTIONS")=="true")Console.WriteLine("SKIP actual SendInput on headless CI; covered by interactive Sandbox fixture");else AutoTypeInput();FileRepair(root);
        }
        static void ReferenceImportScenarios(KdbxStore store,string sourceId){
            using(var imported=PasswordImport.Parse("name,url,username,password\nLinked,https://example.org/login,synthetic@example.com,Synthetic-new!",store.Entries))
                Check("import-resolved-shared-login-and-password-is-duplicate",!imported.Rows.Single().Selectable);
            var alias=new LoginEntry{Name="Linked alias",Kind="site",Target="https://example.net/",Login="different-local",Login2=KdbxStore.Reference(sourceId,'U'),Password=KdbxStore.Reference(sourceId,'P')};store.Entries.Add(alias);store.Save();
            using(var imported=PasswordImport.Parse("Title,URL,Username,Password\nAlias,https://example.net/login,synthetic@example.com,Synthetic-new!",store.Entries))
                Check("import-resolved-secondary-login-is-duplicate",!imported.Rows.Single().Selectable);
            var broken=new LoginEntry{Name="Missing source",Kind="site",Target="https://broken.example/",Login="known-user",Password=KdbxStore.Reference(new string('a',32),'P')};store.Entries.Add(broken);store.Save();
            try {using(var imported=PasswordImport.Parse("name,url,username,password\nBroken,https://broken.example/login,known-user,Synthetic-new!\nOther,https://new.example/,new-user,Other-new!",store.Entries))
                Check("import-broken-reference-requires-choice-and-keeps-other-rows",imported.Rows[0].Selectable&&!imported.Rows[0].DefaultSelected&&imported.Rows[0].Status.Contains("ссылк")&&imported.Rows[1].DefaultSelected);
            }catch(IOException){Check("import-broken-reference-requires-choice-and-keeps-other-rows",false);}
            store.Entries.Remove(alias);store.Entries.Remove(broken);store.Save();alias.ClearSecrets();broken.ClearSecrets();
        }
        static void MergeLocationsAndDeletions(KdbxStore store,string root,string id,string expectedGroup){
            string source=Path.Combine(root,"location-conflict.kdbx");store.SaveBeforeMerge(source);EditNative(source,other=>{var e=other.RootGroup.FindEntry(new PwUuid(KeePassLib.Utility.MemUtil.HexStringToByteArray(id)),true);e.ParentGroup.Entries.Remove(e);other.RootGroup.AddEntry(e,true);e.LocationChanged=DateTime.UtcNow.AddMinutes(2);});
            using(var p=store.PreviewMerge(source,Password,null)){Check("merge-moved-account-is-a-conflict",p.Conflicts.Any(c=>c.Id==id));p.Conflicts.First(c=>c.Id==id).Choice="Эта база";store.ApplyMerge(p);store.Save();}Check("merge-local-choice-keeps-selected-group",store.Entries.Single(e=>e.Id==id).GroupId==expectedGroup);
            store.SaveBeforeMerge(source);EditNative(source,other=>{var e=other.RootGroup.FindEntry(new PwUuid(KeePassLib.Utility.MemUtil.HexStringToByteArray(id)),true);e.ParentGroup.Entries.Remove(e);other.DeletedObjects.Add(new PwDeletedObject(e.Uuid,DateTime.UtcNow.AddMinutes(3)));});
            using(var p=store.PreviewMerge(source,Password,null)){Check("merge-final-deletion-has-explicit-choice",p.Conflicts.Single(c=>c.Id==id).OtherDeleted);p.Conflicts.Single(c=>c.Id==id).Choice="Эта база";store.ApplyMerge(p);store.Save();}Check("merge-keep-account-over-remote-deletion",store.Entries.Any(e=>e.Id==id)&&store.Attachments(id).Count==1);
            using(var p=store.PreviewMerge(source,Password,null)){p.Conflicts.Single(c=>c.Id==id).Choice="Вторая копия";store.ApplyMerge(p);store.Save();}Check("merge-choose-remote-deletion",!store.Entries.Any(e=>e.Id==id));
            string live=Path.Combine(root,"live-after-deletion.kdbx");File.Copy(Path.Combine(root,"other.kdbx"),live);using(var p=store.PreviewMerge(live,Password,null)){Check("merge-local-deletion-conflicts-with-remote-record",p.Conflicts.Single(c=>c.Id==id).LocalDeleted);p.Conflicts.Single(c=>c.Id==id).Choice="Вторая копия";store.ApplyMerge(p);store.Save();}Check("merge-remote-choice-restores-finally-deleted-account",store.Entries.Any(e=>e.Id==id)&&store.Entries.Single(e=>e.Id==id).GroupId==expectedGroup);
        }
        static void EditNative(string path,Action<PwDatabase> edit){var db=new PwDatabase();try{var key=new CompositeKey();key.AddUserKey(new KcpPassword(Password));KdbxSafety.OpenDatabase(db,path,key,null);edit(db);db.Save(null);}finally{db.Close();}}
        static void AutoTypeInput(){using(var window=new Form{Text="Synthetic AutoType Login1",Size=new System.Drawing.Size(500,230),StartPosition=FormStartPosition.CenterScreen,TopMost=true}){
            var user=new TextBox{Top=25,Left=20,Width=400,TabIndex=0};var password=new TextBox{Top=65,Left=20,Width=400,TabIndex=1};var extra=new TextBox{Top=105,Left=20,Width=400,TabIndex=2};window.Controls.AddRange(new Control[]{user,password,extra});Exception error=null;
            window.Shown+=async(s,e)=>{KdbxStore db=null;try{var input=OpenInputDesktop(0,false,1);Console.WriteLine("DESKTOP session="+System.Diagnostics.Process.GetCurrentProcess().SessionId+" thread="+DesktopName(GetThreadDesktop(GetCurrentThreadId()))+" input="+DesktopName(input)+" foreground="+Win.Foreground);if(input!=IntPtr.Zero)CloseDesktop(input);db=KdbxStore.Create(Password,null);var account=new LoginEntry{Name="Synthetic app",Kind="app",Target=Application.ExecutablePath,Login="synthetic-user",Password="Literal {TAB} + ^ %!",CustomFields=new System.Collections.Generic.List<AccountSecretField>{new AccountSecretField{Name="Token",Value="Synthetic-token"}}};db.Entries.Add(account);db.Save();string reason;var target=DesktopTarget.Create(Application.ExecutablePath,out reason);typeof(Win).GetMethod("ShowWindow",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{window.Handle,5});window.Activate();Win.Focus(window.Handle);user.Focus();await System.Threading.Tasks.Task.Delay(200);bool ok=await ApplicationAutoType.Run(account,db,"{DELAY=1}{USERNAME}{TAB}{PASSWORD}{TAB}{S:Token}",window.Handle,target,CancellationToken.None);Console.WriteLine("INPUT completed="+ok+" user="+user.Text+" password="+password.Text+" extra="+extra.Text+" foreground="+Win.IsForeground(window.Handle));Check("autotype-real-input-fields-and-literal-secret",ok&&user.Text=="synthetic-user"&&password.Text=="Literal {TAB} + ^ %!"&&extra.Text=="Synthetic-token");
                user.Text=password.Text=extra.Text="";user.Focus();using(var cancel=new CancellationTokenSource()){cancel.CancelAfter(100);ok=await ApplicationAutoType.Run(account,db,"{DELAY 300}{PASSWORD}",window.Handle,target,cancel.Token);Check("autotype-cancelled-before-password-no-input",!ok&&user.Text==""&&password.Text=="");}
                var task=ApplicationAutoType.Run(account,db,"{DELAY 300}{PASSWORD}",window.Handle,target,CancellationToken.None);await System.Threading.Tasks.Task.Delay(50);db.Save();ok=await task;Check("autotype-stops-when-record-revision-changes",!ok&&user.Text=="");
                task=ApplicationAutoType.Run(account,db,"{DELAY 300}{PASSWORD}",window.Handle,target,CancellationToken.None);await System.Threading.Tasks.Task.Delay(50);using(var other=new Form{Text="Synthetic changed focus"}){other.Show();Win.Focus(other.Handle);ok=await task;Check("autotype-focus-change-no-password-in-other-window",!ok&&user.Text==""&&password.Text=="");other.Close();}Win.Focus(window.Handle);user.Focus();
                task=ApplicationAutoType.Run(account,db,"{DELAY 300}{PASSWORD}",window.Handle,target,CancellationToken.None);await System.Threading.Tasks.Task.Delay(50);db.Lock();ok=await task;Check("autotype-lock-stops-pending-input",!ok&&user.Text=="");
            }catch(Exception ex){error=ex;}finally{if(db!=null)db.Lock();window.Close();}};Application.Run(window);if(error!=null)throw error;
        }}
        static void FileRepair(string root){string original=Path.Combine(root,"original-vault"),copy=Path.Combine(root,"repaired-vault");string input=Path.Combine(root,"keep.txt");File.WriteAllText(input,"Synthetic preserved document");string largeName=new string('L',200)+".txt";string longInput=Path.Combine(root,largeName);File.WriteAllText(SafePaths.Native(longInput),"Synthetic long filename");
            Console.WriteLine("PHASE create "+ComponentResources.RuntimeId);using(var client=new FileVaultClient(original,Password,true)){client.Import(input,"/keep.txt",false);client.Import(longInput,"/"+largeName,false);}
            string c9s=Directory.GetDirectories(Path.Combine(original,"d"),"*.c9s",SearchOption.AllDirectories).Single();Directory.Move(c9s,Path.Combine(Path.GetDirectoryName(c9s),"AAAAAAAAAAAAAAAAAAAAAAAAAAA.c9s"));
            var hashes=Directory.GetFiles(original,"*",SearchOption.AllDirectories).ToDictionary(f=>f.Substring(original.Length),f=>Hash(f));
            Console.WriteLine("PHASE original-health");using(var admin=new FileVaultClient(original,"",false,default(CancellationToken),false,true)){var health=admin.Call("health",Password);Check("corrupt-vault-detected",Convert.ToInt32(health["warnings"])+Convert.ToInt32(health["critical"])>0);Check("repair-original-without-copy-marker-refused",Fails(()=>admin.Call("repair",Password)));}
            PlainFileCopy.Copy(original,copy,default(CancellationToken));File.WriteAllText(Path.Combine(copy,".winup-repair-copy"),"WUR1:synthetic");using(var admin=new FileVaultClient(copy,"",false,default(CancellationToken),false,true)){var fixedResult=admin.Call("repair",Password);Check("native-cryptofs-fix-applied-and-rechecked",Convert.ToInt32(fixedResult["fixed"])>=1&&Convert.ToInt32(fixedResult["warnings"])==0&&Convert.ToInt32(fixedResult["critical"])==0);}
            Check("repair-leaves-original-byte-identical",hashes.All(pair=>Hash(original+pair.Key)==pair.Value));
            using(var client=new FileVaultClient(copy,Password,false)){string output=Path.Combine(root,"recovered.txt");client.Call("export","/"+largeName,output);Check("repaired-document-original-name-and-content",File.ReadAllBytes(output).SequenceEqual(File.ReadAllBytes(SafePaths.Native(longInput))));string other=Path.Combine(root,"other-recovered.txt");client.Call("export","/keep.txt",other);Check("repair-preserves-unaffected-document",File.ReadAllBytes(input).SequenceEqual(File.ReadAllBytes(other)));}
        }
        static string Hash(string path){using(var sha=System.Security.Cryptography.SHA256.Create())using(var input=File.OpenRead(path))return Convert.ToBase64String(sha.ComputeHash(input));}
    }
}
